### ISSUE TITLE
Error while downloading a course

### ISSUE THREAD

**Issue by cilgin** [wilddom/memrise2anki-extension#101]
Hello!
I've been using this extension for a while but lately I keep getting an error whenever I try to download a course. I'm copying the error I get down below.

-----

Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-07-20 21:31:33

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Harvey\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\importer.py", line 854, in importCourse
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "C:\Users\Harvey\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\importer.py", line 150, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "C:\Users\Harvey\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 862, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "C:\Users\Harvey\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 633, in loadCourse
    level = self.loadLevel(course, levelIndex)
  File "C:\Users\Harvey\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 717, in loadLevel
    thingData = self.service.loadThingData(thingId)
  File "C:\Users\Harvey\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 905, in loadThingData
    response = self.openWithRetry(thingUrl)
  File "C:\Users\Harvey\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 819, in openWithRetry
    return self.opener.open(url)
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "C:\Users\Harvey\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 798, in https_open
    return self.do_open_wrapped(http.client.HTTPSConnection, req, context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\Harvey\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 788, in do_open_wrapped
    response = self.do_open(http_class, req, **http_conn_args)
  File "urllib\request.py", line 1353, in do_open
urllib.error.URLError: <urlopen error <urlopen error [WinError 10054] Une connexion existante a dû être fermée par l’hôte distant>>

**Comment by wilddom** [comment]
See #102
