### ISSUE TITLE
Error importing cards: 'ModelManager' object has no attribute 'all_names'

### ISSUE THREAD

**Issue by twoofclubs** [wilddom/memrise2anki-extension#108]
Hi,

I could install the add-on fine, but got the following error message when I tried to import a course, after the course reached 100%. The deck is created but no cards are in it. 

Error message:

Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-01-02 21:08:02

Caught exception:
Traceback (most recent call last):
  File "C:\Users\[USER]\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 884, in importCourse
    model = self.modelMapper.getModel(thing, deck)
  File "C:\Users\[USER]\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 384, in getModel
    self.__fillModelSelection()
  File "C:\Users\[USER]\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 263, in __fillModelSelection
    for name in sorted(self.col.models.all_names()):
AttributeError: 'ModelManager' object has no attribute 'all_names'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[USER]\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 950, in importCourse
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "C:\Users\[USER]\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 884, in importCourse
    model = self.modelMapper.getModel(thing, deck)
  File "C:\Users\[USER]\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 384, in getModel
    self.__fillModelSelection()
  File "C:\Users\[USER]\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 263, in __fillModelSelection
    for name in sorted(self.col.models.all_names()):
AttributeError: 'ModelManager' object has no attribute 'all_names'

**Comment by wilddom** [comment]
You should update Anki, the current version is 2.1.49
