### ISSUE TITLE
Error with Anki Import

### ISSUE THREAD

**Issue by mashiyatsaif** [wilddom/memrise2anki-extension#110]
Used the newest release from 12 days ago.
Error here:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2022-01-09 00:50:39

Caught exception:
Traceback (most recent call last):
  File "C:\Users\mashi\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 884, in importCourse
    model = self.modelMapper.getModel(thing, deck)
  File "C:\Users\mashi\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 384, in getModel
    self.__fillModelSelection()
  File "C:\Users\mashi\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 263, in __fillModelSelection
    for name in sorted(self.col.models.all_names()):
AttributeError: 'ModelManager' object has no attribute 'all_names'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mashi\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 950, in importCourse
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "C:\Users\mashi\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 884, in importCourse
    model = self.modelMapper.getModel(thing, deck)
  File "C:\Users\mashi\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 384, in getModel
    self.__fillModelSelection()
  File "C:\Users\mashi\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 263, in __fillModelSelection
    for name in sorted(self.col.models.all_names()):
AttributeError: 'ModelManager' object has no attribute 'all_names'

**Comment by wilddom** [comment]
You should update Anki, the latest version is 2.1.49
