### ISSUE TITLE
"TypeError: 'NoneType' object is not subscriptable" when download

### ISSUE THREAD

**Issue by igormicadei** [wilddom/memrise2anki-extension#115]
This error is thrown when I try to download the course Russian-1.
My user in memrise and in the Anki is in pt-BR.

`Informações de Depuração:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-28 10:13:58

Caught exception:
Traceback (most recent call last):
  File "C:\Users\072976631\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 856, in importCourse
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "C:\Users\072976631\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 151, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "C:\Users\072976631\AppData\Roaming\Anki2\addons21\memrise2anki\memrise.py", line 870, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "C:\Users\072976631\AppData\Roaming\Anki2\addons21\memrise2anki\memrise.py", line 623, in loadCourse
    course.title = sanitizeName(courseData["session"]["course"]["name"], "Course")
TypeError: 'NoneType' object is not subscriptable
`

**Comment by wilddom** [comment]
See  #113 

The addon is unfortunately broken due to changes from Memrise. And I don't have the time to work on it.
