### ISSUE TITLE
Converting issue

### ISSUE THREAD

**Issue by Mlukni22** [wilddom/memrise2anki-extension#116]
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 8.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-09-02 19:05:54

Caught exception:
Traceback (most recent call last):
  File "C:\Users\user1\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\importer.py", line 856, in importCourse
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "C:\Users\user1\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\importer.py", line 151, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "C:\Users\user1\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 872, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "C:\Users\user1\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 623, in loadCourse
    course.title = sanitizeName(courseData["session"]["course"]["name"], "Course")
TypeError: 'NoneType' object is not subscriptable

**Comment by wilddom** [comment]
See #113
