### ISSUE TITLE
Unable to import decks from Memrise to Anki

### ISSUE THREAD

**Issue by tamihu** [wilddom/memrise2anki-extension#118]
Debug info:
Anki 2.1.57 (6b7d372c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-02-01 20:07:37

Caught exception:
Traceback (most recent call last):
  File "C:\Users\TAMI\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 856, in importCourse
  File "C:\Users\TAMI\AppData\Roaming\Anki2\addons21\memrise2anki\importer.py", line 151, in run
  File "C:\Users\TAMI\AppData\Roaming\Anki2\addons21\memrise2anki\memrise.py", line 870, in loadCourse
  File "C:\Users\TAMI\AppData\Roaming\Anki2\addons21\memrise2anki\memrise.py", line 623, in loadCourse
TypeError: 'NoneType' object is not subscriptable

**Comment by wilddom** [comment]
See #113
At the moment I'm busy with other things, so unfortunately there are no plans to fix the addon.
