### ISSUE TITLE
Missing columns

### ISSUE THREAD

**Issue by FrankEular** [wilddom/memrise2anki-extension#32]
URL: http://www.memrise.com/course/58727/irregular-french-verbs-2/

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "/home/gaussfrank/Documents/Anki/addons/Memrise_Course_Importer/importer.py", line 146, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "/home/gaussfrank/Documents/Anki/addons/Memrise_Course_Importer/memrise.py", line 725, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "/home/gaussfrank/Documents/Anki/addons/Memrise_Course_Importer/memrise.py", line 555, in loadCourse
    level = self.loadLevel(course, levelIndex)
  File "/home/gaussfrank/Documents/Anki/addons/Memrise_Course_Importer/memrise.py", line 636, in loadLevel
    thing = thingLoader.loadThing(thingRowData, self.service.toAbsoluteMediaUrl)
  File "/home/gaussfrank/Documents/Anki/addons/Memrise_Course_Importer/memrise.py", line 460, in loadThing
    cell = row['columns'][unicode(column.index)]
KeyError: u'3'

**Comment by wilddom** [comment]
Sometimes columns were missing, it should be handled correctly now.
