### ISSUE TITLE
Error occured while importing

### ISSUE THREAD

**Issue by FrankEular** [wilddom/memrise2anki-extension#37]
http://www.memrise.com/course/323711/learn-french-7329-words-122h/

Traceback (most recent call last):
  File "/home/gaussfrank/Documents/Anki/addons/Memrise_Course_Importer/importer.py", line 146, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "/home/gaussfrank/Documents/Anki/addons/Memrise_Course_Importer/memrise.py", line 725, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "/home/gaussfrank/Documents/Anki/addons/Memrise_Course_Importer/memrise.py", line 555, in loadCourse
    level = self.loadLevel(course, levelIndex)
  File "/home/gaussfrank/Documents/Anki/addons/Memrise_Course_Importer/memrise.py", line 629, in loadLevel
    level.pool.schedule.add(self.loadScheduleInfo(userData, level.pool))
  File "/home/gaussfrank/Documents/Anki/addons/Memrise_Course_Importer/memrise.py", line 583, in loadScheduleInfo
    scheduleInfo.correct = data['total_correct']
KeyError: 'total_correct'

**Comment by wilddom** [comment]
This has already been fixed in #34, just update the addon.
