### ISSUE TITLE
"invalid credential"

### ISSUE THREAD

**Issue by mtthth** [wilddom/memrise2anki-extension#40]
From now how, I cannot use the extension.

When I launch the extension, it asks me my login/password (btw i was l previously logged, and for months), and either answers 

> invalid credential

or

```
Traceback (most recent call last):
  File "C:\Users\Matthieu\Documents\Anki\addons\Memrise_Course_Importer\importer.py", line 210, in accept
    if self.memriseService.login(self.usernameLineEdit.text(),self.passwordLineEdit.text()):
  File "C:\Users\Matthieu\Documents\Anki\addons\Memrise_Course_Importer\memrise.py", line 736, in login
    for field in form.findAll("input"):
AttributeError: 'NoneType' object has no attribute 'findAll'
```

**Comment by wilddom** [comment]
Memrise now consequently uses https, the latest commit should fix the issue.
