### ISSUE TITLE
Bug Report when attempting import

### ISSUE THREAD

**Issue by adoette** [wilddom/memrise2anki-extension#45]
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\importer.py", line 146, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "C:\Users\USERNAME\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 752, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "C:\Users\USERNAME\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 568, in loadCourse
    level = self.loadLevel(course, levelIndex)
  File "C:\Users\USERNAME\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 644, in loadLevel
    level.pool.schedule.add(self.loadScheduleInfo(userData, level.pool))
  File "C:\Users\USERNAME\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 601, in loadScheduleInfo
    scheduleInfo.due = utcToLocal(datetime.datetime.strptime(data['next_date'], "%Y-%m-%dT%H:%M:%S"))
  File "_strptime.py", line 328, in _strptime
ValueError: unconverted data remains: Z

**Comment by wilddom** [comment]
Memrise changed the date and time format, it should be fixed now.
