### ISSUE TITLE
Error importing course - KeyError: 'pools'

### ISSUE THREAD

**Issue by figdanivi** [wilddom/memrise2anki-extension#50]
I'm encountering the following error when attempting to import a course:

```
Traceback (most recent call last):
  File "/home/figdanivi/.local/share/Anki2/addons/Memrise_Course_Importer/importer.py", line 146, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "/home/figdanivi/.local/share/Anki2/addons/Memrise_Course_Importer/memrise.py", line 776, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "/home/figdanivi/.local/share/Anki2/addons/Memrise_Course_Importer/memrise.py", line 579, in loadCourse
    level = self.loadLevel(course, levelIndex)
  File "/home/figdanivi/.local/share/Anki2/addons/Memrise_Course_Importer/memrise.py", line 647, in loadLevel
    pool = self.loadPool(levelData["pools"][unicode(poolId)])
KeyError: 'pools'
```

Please tell me if you would like me to provide any additional information.

**Comment by wilddom** [comment]
Duplicate of #49
