### ISSUE TITLE
Problem with downloading media files

### ISSUE THREAD

**Issue by Iaith** [wilddom/memrise2anki-extension#54]
After the updating to 1.0.6 i get the following error

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\importer.py", line 146, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "C:\Users\...\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 782, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "C:\Users\...\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 578, in loadCourse
    level = self.loadLevel(course, levelIndex)
  File "C:\Users\...\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 689, in loadLevel
    self.notify('thingLoaded', thing)
  File "C:\Users\...\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 559, in notify
    getattr(observer, signal)(*attrs, **kwargs)
  File "C:\Users\...\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\importer.py", line 70, in thingLoaded
    self.downloadMedia(thing)
  File "C:\Users\...\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\importer.py", line 48, in downloadMedia
    image.localUrl = self.sender.download(image.remoteUrl)
  File "C:\Users\...\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\importer.py", line 110, in download
    return self.memriseService.downloadMedia(url, skipExisting=self.skipExistingMedia)
  File "C:\Users\...\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 880, in downloadMedia
    data = self.openWithRetry(url).read()
  File "C:\Users\...\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 745, in openWithRetry
    return self.opener.open(url)
  File "urllib2.py", line 392, in open
  File "urllib2.py", line 254, in get_type
ValueError: unknown url type: uploads/things/images/31809167_160129_0529_56.gif

Thanks in advance

**Comment by wilddom** [comment]
Could you please try the latest commit and report back?

**Comment by Iaith** [comment]
Do i just download the zip again?

**Comment by wilddom** [comment]
Just replace one file:
https://raw.githubusercontent.com/wilddom/memrise2anki-extension/master/Memrise_Course_Importer/memrise.py

**Comment by Iaith** [comment]
It worked thanks a lot
