### ISSUE TITLE
timestamp error

### ISSUE THREAD

**Issue by Shiro00000** [wilddom/memrise2anki-extension#69]
I wanna download a course with 2200 words and get this error:

Traceback (most recent call last):
  File "C:\Users\Username\Documents\Anki\addons\Memrise_Course_Importer\importer.py", line 146, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "C:\Users\Username\Documents\Anki\addons\Memrise_Course_Importer\memrise.py", line 788, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "C:\Users\Username\Documents\Anki\addons\Memrise_Course_Importer\memrise.py", line 578, in loadCourse
    level = self.loadLevel(course, levelIndex)
  File "C:\Users\Username\Documents\Anki\addons\Memrise_Course_Importer\memrise.py", line 679, in loadLevel
    level.pool.schedule.add(self.loadScheduleInfo(userData, level.pool))
  File "C:\Users\Username\Documents\Anki\addons\Memrise_Course_Importer\memrise.py", line 617, in loadScheduleInfo
    scheduleInfo.due = utcToLocal(datetime.datetime.strptime(data['next_date'], "%Y-%m-%dT%H:%M:%SZ"))
  File "C:\Users\Username\Documents\Anki\addons\Memrise_Course_Importer\memrise.py", line 8, in utcToLocal
    localDt = datetime.datetime.fromtimestamp(timestamp)
ValueError: timestamp out of range for platform localtime()/gmtime() function

could it be the timestamp is too big?
I'm using the version for 2.0

**Comment by wilddom** [comment]
I won't work on the old version, could you please update anki to 2.1 and report back? And which operating system do you use?

**Comment by Shiro00000** [comment]
Thank you for the quick reply. I updated and it is downloading now, I will report back. Between, did you notice memrise is moving all community-made courses? Many users are switching now to anki, so keep up the good work :D

**Comment by Shiro00000** [comment]
I'm sorry, but update did not fix it.

Caught exception:
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\importer.py", line 840, in importCourse
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\importer.py", line 146, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 789, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 579, in loadCourse
    level = self.loadLevel(course, levelIndex)
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 680, in loadLevel
    level.pool.schedule.add(self.loadScheduleInfo(userData, level.pool))
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 618, in loadScheduleInfo
    scheduleInfo.due = utcToLocal(datetime.datetime.strptime(data['next_date'], "%Y-%m-%dT%H:%M:%SZ"))
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\memrise2anki-extension-master\memrise.py", line 9, in utcToLocal
    localDt = datetime.datetime.fromtimestamp(timestamp)
<class 'OSError'>: [Errno 22] Invalid argument

**Comment by wilddom** [comment]
I tried to fix this, but not sure if it works as I can't test it right now, could you give it another try?

**Comment by Shiro00000** [comment]
You fixed it, thanks a lot :D

**Comment by Shiro00000** [comment]
ok, mems were imported, althrough i did not check it and they are buggy, but i dont wanna use them anyway, but wanted to tell you
