### ISSUE TITLE
Problem with an Add-on

### ISSUE THREAD

**Issue by Dobtat** [wilddom/memrise2anki-extension#70]
It seems like I've installed the add-on, but something went wrong

https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\addons.py", line 41, in loadAddons
  File "C:\Users\Scorpions\AppData\Roaming\Anki2\addons\importer.py", line 3, in <module>
    import http.cookiejar, os.path, uuid, sys, datetime, re
ImportError: No module named http.cookiejar
Traceback (most recent call last):
  File "aqt\addons.py", line 41, in loadAddons
  File "C:\Users\Scorpions\AppData\Roaming\Anki2\addons\memrise.py", line 1, in <module>
    import urllib.request, urllib.error, urllib.parse, http.cookiejar, urllib.request, urllib.parse, urllib.error, http.client, urllib.parse
ImportError: No module named request
Traceback (most recent call last):
  File "aqt\addons.py", line 41, in loadAddons
  File "C:\Users\Scorpions\AppData\Roaming\Anki2\addons\memrise_markdown.py", line 2, in <module>
    from . import mistune
ValueError: Attempted relative import in non-package
Traceback (most recent call last):
  File "aqt\addons.py", line 41, in loadAddons
  File "C:\Users\Scorpions\AppData\Roaming\Anki2\addons\oembed.py", line 1, in <module>
    import json, urllib.request, urllib.parse
ImportError: No module named request
Traceback (most recent call last):
  File "aqt\addons.py", line 41, in loadAddons
  File "C:\Users\Scorpions\AppData\Roaming\Anki2\addons\__init__.py", line 1, in <module>
    from . import importer
ValueError: Attempted relative import in non-package

**Comment by wilddom** [comment]
The addon has been updated for anki 2.1 and this seems to be anki 2.0.
