### ISSUE TITLE
Import doesn't work

### ISSUE THREAD

**Issue by Igeljaeger** [wilddom/memrise2anki-extension#88]
(flatpak version)
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.1 Qt 5.15.0 PyQt 5.15.0
Platform: Pop!_OS 20.04 LTS x86_64
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-09 22:40:40
Add-ons possibly involved: ⁨memrise2anki-extension-master⁩

Caught exception:
Traceback (most recent call last):
  File "/home/igel/.var/app/net.ankiweb.Anki/data/Anki2/addons21/memrise2anki-extension-master/importer.py", line 849, in importCourse
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/home/igel/.var/app/net.ankiweb.Anki/data/Anki2/addons21/memrise2anki-extension-master/importer.py", line 150, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "/home/igel/.var/app/net.ankiweb.Anki/data/Anki2/addons21/memrise2anki-extension-master/memrise.py", line 845, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "/home/igel/.var/app/net.ankiweb.Anki/data/Anki2/addons21/memrise2anki-extension-master/memrise.py", line 610, in loadCourse
    course.title = sanitizeName(courseData["session"]["course"]["name"], "Course")
TypeError: 'NoneType' object is not subscriptable

**same errors on the normal version from the repo:**

Debug info:
Anki 2.1.15 (442df9d6) Python 3.8.2 Qt 5.12.8 PyQt 5.14.1
Platform: Pop!_OS 20.04 LTS x86_64
Flags: frz=False ao=True sv=1
Add-ons possibly involved: memrise2anki-extension-master

Caught exception:
File "/home/igel/.local/share/Anki2/addons21/memrise2anki-extension-master/importer.py", line 849, in importCourse
raise exc_info0.with_traceback(exc_info[2])
File "/home/igel/.local/share/Anki2/addons21/memrise2anki-extension-master/importer.py", line 150, in run
course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
File "/home/igel/.local/share/Anki2/addons21/memrise2anki-extension-master/memrise.py", line 845, in loadCourse
return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
File "/home/igel/.local/share/Anki2/addons21/memrise2anki-extension-master/memrise.py", line 610, in loadCourse
course.title = sanitizeName(courseData["session"]["course"]["name"], "Course")
<class 'TypeError'>: 'NoneType' object is not subscriptable

The add on was installed the manual way on both versions.

I'm not a coder so I'm not sure how to interpret or solve this myself.

**Comment by Igeljaeger** [comment]
same errors on normal version:


Debug info:
Anki 2.1.15 (442df9d6) Python 3.8.2 Qt 5.12.8 PyQt 5.14.1
Platform: Pop!_OS 20.04 LTS x86_64
Flags: frz=False ao=True sv=1
Add-ons possibly involved: memrise2anki-extension-master

Caught exception:
  File "/home/igel/.local/share/Anki2/addons21/memrise2anki-extension-master/importer.py", line 849, in importCourse
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/home/igel/.local/share/Anki2/addons21/memrise2anki-extension-master/importer.py", line 150, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "/home/igel/.local/share/Anki2/addons21/memrise2anki-extension-master/memrise.py", line 845, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "/home/igel/.local/share/Anki2/addons21/memrise2anki-extension-master/memrise.py", line 610, in loadCourse
    course.title = sanitizeName(courseData["session"]["course"]["name"], "Course")
<class 'TypeError'>: 'NoneType' object is not subscriptable

**Comment by eddielewis** [comment]
I found a fix for this. I replaced every occurrence of "www.memrise" with "app.memrise" inside memrise.py within the Anki addon diretory.

**Comment by LeavesEatingCow** [comment]
@eddielewis Thank you soo much!

**Comment by Igeljaeger** [comment]
This seems to have solved it. Thank you! @eddielewis

**Comment by eddielewis** [comment]
@Igeljaeger sorry I don't have any idea what is wrong with yours, mine worked perfectly after the fix. You'll have to wait for the maintainer to have a look.

**Comment by wilddom** [comment]
Could you try with the latest [1.2.2](https://github.com/wilddom/memrise2anki-extension/releases/tag/v1.2.2) release? And if that error still occurs please post the course url.

**Comment by wilddom** [comment]
This has been fixed in the latest [1.2.4](https://github.com/wilddom/memrise2anki-extension/releases/tag/v1.2.4) release
