### ISSUE TITLE
Can't select note type

### ISSUE THREAD

**Issue by xd-Neji** [wilddom/memrise2anki-extension#91]
I keep receiving this error after selecting a note type.

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-20 21:51:52

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Necip\AppData\Roaming\Anki2\addons21\Memrise2Anki\importer.py", line 877, in importCourse
    model = self.modelMapper.getModel(thing, deck)
  File "C:\Users\Necip\AppData\Roaming\Anki2\addons21\Memrise2Anki\importer.py", line 386, in getModel
    self.models[thing.pool.id] = self.__loadModel(thing, deck)
  File "C:\Users\Necip\AppData\Roaming\Anki2\addons21\Memrise2Anki\importer.py", line 370, in __loadModel
    self.col.models.add(model)
  File "anki\models.py", line 220, in add
  File "anki\models.py", line 87, in save
  File "anki\models.py", line 231, in update
  File "anki\rsbackend_gen.py", line 414, in add_or_update_notetype
  File "anki\rsbackend.py", line 267, in _run_command
anki.rsbackend.InvalidInput: InvalidInput { info: "1 template required" }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Necip\AppData\Roaming\Anki2\addons21\Memrise2Anki\importer.py", line 943, in importCourse
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "C:\Users\Necip\AppData\Roaming\Anki2\addons21\Memrise2Anki\importer.py", line 877, in importCourse
    model = self.modelMapper.getModel(thing, deck)
  File "C:\Users\Necip\AppData\Roaming\Anki2\addons21\Memrise2Anki\importer.py", line 386, in getModel
    self.models[thing.pool.id] = self.__loadModel(thing, deck)
  File "C:\Users\Necip\AppData\Roaming\Anki2\addons21\Memrise2Anki\importer.py", line 370, in __loadModel
    self.col.models.add(model)
  File "anki\models.py", line 220, in add
  File "anki\models.py", line 87, in save
  File "anki\models.py", line 231, in update
  File "anki\rsbackend_gen.py", line 414, in add_or_update_notetype
  File "anki\rsbackend.py", line 267, in _run_command
anki.rsbackend.InvalidInput: <unprintable InvalidInput object>

**Comment by wilddom** [comment]
I can't reproduce this error. Could you give some more details what exactly you are doing?

**Comment by xd-Neji** [comment]
I click on import memrise course select create new deck then put the URL of Japanese no script 2 and click ok. Once it has done downloading I selected new note type and it crashed. However I tried again but selected the basic note type and it worked fine.

**Comment by wilddom** [comment]
Could you post the course url?

**Comment by xd-Neji** [comment]
https://app.memrise.com/course/5503974/japanese-2-no-script/

**Comment by wilddom** [comment]
Okay, thank you. I tried to fix that already (#84), but it's a difficult one. Obviously there is an inconsitency in the data. I have a fix ready and will post a new release soon.
