### ISSUE TITLE
Some decks are completely downloaded - connection is OK but addon says no

### ISSUE THREAD

**Issue by gabriellluz** [wilddom/memrise2anki-extension#92]
Hi.

I'm trying to download a few decks but after sometime the addon simply crashes with the message below.
The decks I've tried:
https://app.memrise.com/course/125955/russo-para-brasileiros/
https://app.memrise.com/course/1271778/russo-com-victoria-yevtushenko-a1/
https://app.memrise.com/course/1305254/polish-2/

```
Caught exception:
Traceback (most recent call last):
  File "/media/segundohd/anki-client/data/addons21/2071525018/importer.py", line 849, in importCourse
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/media/segundohd/anki-client/data/addons21/2071525018/importer.py", line 150, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "/media/segundohd/anki-client/data/addons21/2071525018/memrise.py", line 792, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "/media/segundohd/anki-client/data/addons21/2071525018/memrise.py", line 576, in loadCourse
    level = self.loadLevel(course, levelIndex)
  File "/media/segundohd/anki-client/data/addons21/2071525018/memrise.py", line 670, in loadLevel
    thingData = self.service.loadThingData(thingId)
  File "/media/segundohd/anki-client/data/addons21/2071525018/memrise.py", line 835, in loadThingData
    response = self.openWithRetry(thingUrl)
  File "/media/segundohd/anki-client/data/addons21/2071525018/memrise.py", line 749, in openWithRetry
    return self.opener.open(url)
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 542, in _open
  File "urllib/request.py", line 502, in _call_chain
  File "/media/segundohd/anki-client/data/addons21/2071525018/memrise.py", line 728, in https_open
    return self.do_open_wrapped(http.client.HTTPSConnection, req, context=self._context, check_hostname=self._check_hostname)
  File "/media/segundohd/anki-client/data/addons21/2071525018/memrise.py", line 718, in do_open_wrapped
    response = self.do_open(http_class, req, **http_conn_args)
  File "urllib/request.py", line 1322, in do_open
urllib.error.URLError: <urlopen error <urlopen error [Errno -2] Name or unknown service>>
```

Please try to download all of them above and see if the same error occurs to you.

Thank you a lot for this amazing addon.

**Comment by gabriellluz** [comment]
It seems to me my firewall was blocking the connection. Temporarily disabling it did the trick.
